---
title: "Итоговый отчет"
subtitle: "Проектное задание по курсу Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Обзор этапа

### **Цель:** предоставить итоговый вариант полного отчета по проекту. В общем, этап предполагает сведение всех результатов вместе, оформление чистовой версии отчета, включающего все требуемые разделы. 


### **Дедлайн:** 14:00 (Мск) 17.12

---

# Итоговый отчет

Итоговый отчет представляет собой законченный и самостоятельный документ формата “Аналитический отчет о проделанной работе”. Итоговый отчет имеет примерно следующую структуру (фактическая структура может отличаться, если это гарантирует улучшение восприятия содержания отчета, а также лучше соответствует характеру работы, полученным результатам и т.д.):

- Титульный лист с указанием темы работы и состава команды

- Вводную часть, описывающую постановку и обоснование вопроса

- Описание данных, разведанализ данных

- Формулировку и обоснование модели или моделей

- Ожидаемые результаты

- Результаты регрессионного анализа

- Анализ результатов, включая результаты проведения статистических тестов или других необходимых процедур

- Ответ на содержательный вопрос в рамках проведенного анализа, при необходимости сопровождаемый уместной визуализацией результатов или аналитическими выкладками на основе проведенного анализа

- Критический анализ полученных результатов, анализ ограничений исследования

- Дискуссионную часть с предложениями по возможному расширению исследования

- Заключение

- Оценку вкладов членов команды в групповую работу

- Необходимые приложения с техническими результатами

- Приложение с кодами

- Необходимые ссылки на источники (литературу или данные)

- Ссылки на необходимые онлайн-приложения (наборы данных, неформатные таблицы или графики и т.п.)

*Итоговый отчет должен быть скомпилирован / сохранен в формате PDF.  Конкретных требований к оформлению итогового отчета не предъявляется, однако оно должно соответствовать условию, что итоговый отчет является самостоятельным аналитическим отчетом, который должен быть понятным и хорошо читаемым потенциально незнакомому с темой и ходом исследования читателю.* 

---

# Что нужно сделать?

1. Обсудить командой состояние вашего отчета. Была ли он одобрен преподавателями? Какие рекомендации / замечания вы получили по поводу черновика отчета?

2. Продолжить работу над анализом ограничений исследования и дискуссионной частью отчета.

3. Свести все результаты вместе, оформить чистовую версию отчета, включающего все требуемые разделы.

4. Загрузить итоговый отчет в формате PDF, заполнив [гугл-форму](https://docs.google.com/forms/d/e/1FAIpQLScWeiQ1jpr4l7Tj1p9FCPosJn9gIrBbAgbuSrSqLB9WLYGotA/viewform?usp=sf_link). Затем, в целях собственного успокоения, лидер может написать Дмитрию Терещенко или любому другому преподавателю о том, что форма заполнена.


---

# Что должно быть в приложениях?

В общем, в приложения выносится информация, которая может быть важна для исследования, но при этом может затруднить чтение основной части отчета. 

Традиционно в приложения выносят: 

- дополнительные графики и таблицы;

- технические подробности обработки и чистки данных.

Такие приложения могут существовать либо в виде “дополнительных листов”, которые помещаются в конце документа, либо в виде ссылок на онлайн-ресурсы (rpbus, GitHub и т. п.). 

Также важным критерием качества работы является полная воспроизводимость исследования, которая означает, что ваши результаты можно повторить в схожих условиях. Для подтверждения воспроизводимости вам нужно сделать в работе ссылку на данные с которым вы работаете, а также на ваш код. Это лучше всего сделать в виде онлайн-приложения.


## Как оценить групповую работу?

Нет (почти) никаких требований к тому, как именно нужно оценивать групповую работу и вклад участников в групповую работу.

Единственное требование: эта оценка должна быть сделана, и все члены команды с ней должны быть согласны.

Мы подразумеваем, что когда в отчете появляется соответствующий раздел, а отчет дается на рассмотрение преподавателям, то все члены команды ознакомились с этим разделом и согласны с ним! Пожалуйста, согласуйте между собой эту оценку, прежде чем вставлять ее в отчет. Этого будет достаточно.

Оценка вклада в групповую работу может положительно или отрицательно повлиять на оценку отдельного члена команды, но только на основе оценки вклада именно этого члена команды.

Пример 1. Кто-то из членов команды ощутимо меньше работал вопреки той нагрузке, которая была согласована внутри команды, например, недоделывал взятую работу, проваливал согласованные с сокомандниками сроки и т.д., мешал тем самым вовремя отчитываться... Если вся команда (включая виновника) согласна с негативной оценкой работы именно этого члена команды, то так и стоит написать в отчете. Оценка всей работы будет основана на качестве отчета, на качестве защиты. Комиссия может решить снизить оценку именно этому провинившемуся перед своей командой человеку, но не остальным членам команды (они и так уже пострадали, работая в этих условиях).

Пример 2. Все работало, как надо, все делали все, как полагается, возможно, вся команда так организовалась и в целом все проявили себя достаточно ответственными и обязательными, старались не подводить друг друга без каких-то серьезных причин и т.д. Об этом так и стоит написать. У кого увидим в отчете именно эти формулировки: минус балл за плагиат!

Пример 2.1. В прошлом примере, возможно, в хорошей скоординированности работы команды есть заслуга лидера (может, и не только). Об этом стоит написать. Не факт, что это приведет к повышению оценки, но почему не отметить факт хорошей организационной работы?

Пример 3. В работе возникали трудности, с которыми было не понятно, что делать, и тогда за их решение кто-то брался, возможно, перевыполняя свои изначально согласованные обязанности. Это не обязательно один и тот же человек, и всех таких стоит отметить. Особенно, когда речь идет о второстепенных по отношению к самому исследованию деталей (оформление отчета, вычитка текста) или о замеченных важных деталях, которые повлияли на ход работы и результат... Смотрите сами.

В любом случае не нужно придумывать какие-то проценты и формальные оценки. Вы не делите пирог общей оценки между собой, достанется всем.


---

# Когда дедлайн? 

Жесткий дедлайн: до 14:00 (Мск) 17 декабря (суббота). 

---

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

[Назад к проектному заданию](project_task.html)

[Назад на страницу курса](../ecox22.html)