---
title: "Постановка вопроса и поиск источника данных"
subtitle: "Проектное задание по курсу Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Обзор этапа

### **Цель:** выбрать, сформулировать и **утвердить у преподавателей** исследовательский вопрос и источник и тип данных

### **Дедлайн:** 20:00 (Мск) 15.10

---

# Исследовательский вопрос

## Что такое исследовательский вопрос?

Это тот содержательный с экономической точки зрения вопрос, поиск ответа на который будет целью вашей проектной работы. Вопрос должен быть поставлен таким образом, чтобы соответствовать логике эконометрического анализа. Примеры "хороших" и "плохих" вопросов мы обсуждали на лекциях и семинарских занятиях.

## Какие исследовательские вопросы допустимы?

Одна из учебных целей проектной работы - развитие навыка работы с моделью множественной линейной регрессии в среднем для анализа причинно-следственных связей. Вопрос должен соответствовать этому направлению работы.

**Недопустимы вопросы** о прогнозировании будущего (это задачи для анализа временных рядов) и о выявлении важных факторов (это задача для экономической или иной теории). 

## Как поставить вопрос?

Допустимы два варианты поставки вопроса и выбоба данных:

1. Сначала вопрос, потом данные.

2. Сначала данные, потом вопрос.

Первый вариант более взрослый. Второй - более учебный и этим более удобный, но вопрос все равно должен быть максимально приближен к настоящему.

---

# Что нужно сделать?

1. Обсудить командой варианты вопросов и данных.

2. Утвердить внутри команды вопрос и данные / источник данных.

3. Необязательно, но желательно: собрать черновые данные для демонстрации формата, объема, качества или т.п.

4. Создать черновик отчета и дать доступ к нему преподавателям.

5. **Дождаться комментариев и замечаний или утверждения вопроса и подтверждения о зачета на этом этапе.**

6. Если у преподавателей есть комментарии и замечания, нужно вернуться к групповому обсуждению и устранить их, сообщить об изменениях преподавателям, вернувшись к п.5. 

---

# Что такое черновик отчёта?

- Онлайн документ, к которому можно предоставить доступ по ссылке. 

- До оформления итогового отчета черновик должен оставаться одним и тем же, постепенно меняясь по ходу работы.

- **На данном этапе** достаточно включить черновые версии пп. 1 - 3 (титульный лист, введение, описание данных). Подробное описание разделов отчета см в [полном задании на проект](project_task.html), раздел "Итоговый отчёт".

---

# Когда дедлайн? 

Жесткий дедлайн: до 20:00 (Мск) 15 октября (воскресенье). До этого времени преподаватели должны утвердить поставленный вопрос и выбранные данные. **Если у преподавателей останутся вопросы или нерешенные комментарии к постановке вопроса или выбору данных, дедлайн не засчитывается.**

**Настоятельно рекомендуем** первую версию чернового отчета с постановкой вопроса и идеями о подходящих данных сделать и прислать уже до начала октября! Тогда у вас будет возможность получить развернутые комментарии и рекомендации по улучшению.

---

# Помощь в поиске данных

Эта короткая инструкция - лишь рекомендация, не обязательно строго следовать ей. Единственное условие, которое мы жестко ставим относительно источников данных - **нельзя использовать данные, выложенные на ресурсе *kaggle*.**

Есть множество баз данных, которые могут вам помочь. Далее приведены ссылки на разные источники или коллекции источников, а также некоторые обзоры коллекций источников. Не старайтесь охватить все-все варианты - это просто невозможно. Постарайтесь сначала определиться если не с вопросом, то хотя бы с направлением, в котором вашей команде интересно работать, это поможет сузить диапазон вариантов данных - финансы, макро, экология, недвижимость, микро, здоровье, климат, эксперименты.... Если вам не нравится, что вы находите, или ненаходите устраивающие вас данные - переключайтесь на другой вопрос и данные. 

## Где искать данные:

1. [Ресурсы, к которым есть доступ из ВШЭ](http://sophist.hse.ru/data_access.shtml)

2. [РМЭЗ (RLMS)](https://www.hse.ru/rlms/) - тоже ВШЭ, но это внутренний ресурс

3. [Росстат](https://rosstat.gov.ru/)

4. [Мировой банк](https://data.worldbank.org/)

5. [Международный валютный фонд](https://www.imf.org/en/Data)

6. [Национальное бюро экономических исследований](https://www.nber.org/research/data?page=1&perPage=50)

7. [Бюро экономического анализа](https://www.bea.gov/data)

8. [Бюро переписи США](https://data.census.gov/cedsci/)

9. [Данные ФБР по преступности](https://www.fbi.gov/services/cjis/ucr/)

10. [Администрация США по энергетике](https://www.eia.gov/opendata/)

11. [Google trends](https://trends.google.ru/trends/)

12. [Портал официальной статистики по Великобритании](https://data.gov.uk/)

13. [Портал открытых данных правительства Москвы](https://data.mos.ru/)

14. [Каталог данных ИНИД](https://www.data-in.ru/data-catalog/)

*Этим, конечно, источники данных не ограничиваются. Если у вас есть идеи или предложения - предлагайте!*

Также рекомендуется познакомиться [со статьей в журнале "Квантиль" о поиске данных в сети](http://quantile.ru/06/06-AT.pdf).

---

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

[Назад к проектному заданию](project_task.html)

[Назад на страницу курса](../ecox22.html)
