---
title: "Проектное задание"
subtitle: "Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Место "Проекта" в курсе

Групповая эмпирическая работа по Эконометрике (далее - “Проект”) - это один из видов работы на курсе “Эконометрика” и соответствующая форма текущего контроля (вес в итоговой оценки за курс - 29%).
Выполнение проекта имеет целью развитие навыков и получения опыта практического применения знаний, навыков и умений в области регрессионного анализа в контексте прикладного эмпирического исследования с целью ответа на содержательный вопрос. Вопрос исследования должен касаться взаимосвязей между некоторыми экономическими величинами, а также возможностей их оценки и анализа методами прикладного регрессионного анализа. Проект также нацелен на развитие у студентов навыков командной и аналитической работы и обоснования результатов этой работы и оформления их в виде письменного аналитического отчета.

[Назад на страницу курса](../ecox22.html)

---

# Организация работы на проектом

Проект является групповой работой и выполняется в малых группах студентов (5-8 человек), формирование которых происходит на основе самоорганизации студентов. Группы формируются в начале семестра и остаются неизменными в течение всей работы над проектом. В течение семестра каждая группа работает над индивидуальным заданием, суть которого сводится к ответу на поставленный экономический вопрос методами регрессионного анализа и критическому анализу результатов этой работы. Выбор непосредственного вопроса и данных для ответа на него является частью задания и выполняется самостоятельно студентами в составе сформированной команды.

Выполнение работы происходит в соответствие с планом, который зафиксирован данным заданием (см далее раздел документа “Примерный план выполнения работы”). По ходу продвижения в работе, студенты получают уточненные задания на каждый этап работы (одинаковые для всех групп), а также индивидуальные рекомендации по выполнению работы, корректировке результатов, доработке уже полученных промежуточных результатов и т.д. от преподавателей в режиме индивидуальных консультаций и в виде обратной связи на предоставляемые промежуточные отчеты. Для контроля за ходом выполнения работы студенты обязаны следовать календарю дедлайнов (см “Календарь дедлайнов”) и отчитываться об определенных этапах работы в установленной форме и в установленный срок. 

Основным итогом работы, который предъявляет команда по завершению работы над проектом, является итоговый отчет о проведенном исследовании (см “Итоговый отчет”). Последним этапом проектной работы является устная защита результатов работы перед комиссией из преподавателей.

---

# Примерный план выполнения работы

Команды должны следовать следующему плану выполнения проекта. Расширенное задание и рекомендации по выполнению каждого непосредственного этапа плана команды будут получать заблаговременно после прохождения отчета или наступления дедлайна по предыдущим этапам работы.

**1. Сбор команды.** Необходимо самоорганизоваться для сбора команды, согласно установленным требованиям. Команда выбирает лидера, который утверждает состав команды у лектора. Далее команда приступает к выполнению групповой работы по плану и в соответствии с получаемыми заданиями.

**2. Постановка и обоснование исследовательского вопроса, выбор источника данных, получение данных.** Команда выбирает направление своего эмпирического исследования, занимается поиском данных, постановкой и обоснованием исследовательского вопроса. Исследовательский вопрос и источник данных согласуется с преподавателями.

**3. Получение данных и уточнение исследовательского вопроса, формулировка первой версии рабочих гипотез исследования, по возможности и предварительной версии ожидаемых результатов.** Фиксируется промежуточный отчет с описанием постановки и актуальности вопроса, описанием источника данных, предварительным описанием рабочих гипотез.

**4. Разведывательный анализ данных.** Начинается фактическая работа с данными. При необходимости проводится чистка данных. Все процедуры обосновываются, и их результаты фиксируются в промежуточных отчетах. Уточняется исследовательский вопрос и его соответствие данным. Выполняется предварительная формулировка модели. Фиксируются ожидаемые результаты. Оформляется первая черновая версия итогового отчета (для будущих разделов фиксируется структура документа).

**5. Регрессионный анализ.** Проводится построение и анализ спецификаций выбранных моделей. Предварительный анализ результатов и по необходимости - корректировка поставленного вопроса или набора данных. Фиксируется вторая черновая версия итогового отчета (как расширение и дополнение предыдущих версий отчета).

**6. Продолжение работы с моделями, оценка регрессий, анализ результатов, проведение необходимых тестов или построение прогнозов.** Уточнение результатов. Критический анализ полученных результатов и их соответствия ожидаемым результатам. Оценка ограничений исследования. Дискуссия. Фиксируется промежуточный отчет о прогрессе.

**7. Оценка вклада в командную работу отдельных членов команды.**

**8. Оформление и сдача итогового отчета.**

**9. Защита проекта.**

---

# Календарь дедлайнов

- *Время всех делайнов по умолчанию 20:00 Московского времени, если иное не указано непосредственно в задании на промежуточный отчет*

- *Некоторые дедлайны могут быть уточнены по зоду курса для лучшего соответствия учебному процессу*

## 1. [Сбор команды](project_task_part01_team.html)

*Сбор команды, выбор лидера, утверждение состава*

### **Требуется:** согласовать состав команды с преподавателями

### **Дедлайн:** 25.09

## 2. Постановка вопроса и поиск источника данных

*Выбор направления исследования и первичная постановка исследовательского вопроса, обоснование его актуальности, выбор источника данных, по возможности сбор данных*

### **Требуется:** предоставить промежуточный отчет с описанием и обоснованием вопроса, ссылки на источники данных или собранные черновые данные

### **Дедлайн:** 15.10

## 3. Разведка

*Разведывательный анализ данных, обоснование соответствия данных поставленному вопросу, по необходимости коррекция вопроса, первичная формулировка модели, формулировка ожидаемых результатов*

### **Требуется:** предоставить промежуточный отчет, соответствующим образом дополняющий предыдущие версии 

### **Дедлайн:** 31.10

## 4. Черновик 1

*Оформление предыдущих версий отчета в черновой вариант итогового отчета, сформированная примерная структура всего итогового отчета, начало работы над регрессионным анализом, по необходимости коррекция набора данных или исследовательского вопроса*

### **Требуется:** предоставить первый черновой вариант отчета

### **Дедлайн:** 7.11

## 5. Черновик 2

*Продвижение в работе с моделями, первичный анализ результатов и доработка моделей и оценок по необходимости, оформление результатов регрессионного анализа и анализа результатов, начало работы над анализом ограничений исследования и дискуссионной части*

### **Требуется:** предоставить вторую черновую версию отчёта

### **Дедлайн:** 28.11

## 6. Итоговый отчет, включая оценку групповой работы

*Сведение всех результатов вместе, оформление чистовой версии отчета, включающего все требуемые разделы. Изменение отчета после этого этапа допускается только в части оценки групповой работы (лидер подтверждает оценки командной работы, в отчет включается соответствующий параграф)*

### **Требуется:** сдать итоговый отчет

### **Дедлайн:** 12.12

## 7. Защита

*Устная групповая защита проектной работы*

### **Требуется:** пройти защиту в установленном формате

*Защита пройдет в течение недели перед сессией второго модуля, точный формат и время проведения будут уточнены во втором модуле*

---

# Итоговый отчет

Итоговый отчет представляет собой законченный и самостоятельный документ формата “Аналитический отчет о проделанной работе”. Итоговый отчет имеет примерно следующую структуру (фактическая структура может отличаться, если это гарантирует улучшение восприятия содержания отчета, а также лучше соответствует характеру работы, полученным результатам и т.д.):

- Титульный лист с указанием темы работы и состава команды

- Вводную часть, описывающую постановку и обоснование вопроса

- Описание данных, разведанализ данных

- Формулировку и обоснование модели или моделей

- Ожидаемые результаты

- Результаты регрессионного анализа

- Анализ результатов, включая результаты проведения статистических тестов или других необходимых процедур

- Ответ на содержательный вопрос в рамках проведенного анализа, при необходимости сопровождаемый уместной визуализацией результатов или аналитическими выкладками на основе проведенного анализа

- Критический анализ полученных результатов, анализ ограничений исследования

- Дискуссионную часть с предложениями по возможному расширению исследования

- Заключение

- Оценку вкладов членов команды в групповую работу

- Необходимые приложения с техническими результатами

- Приложение с кодами

- Необходимые ссылки на источники (литературу или данные)

- Ссылки на необходимые онлайн-приложения (наборы данных, неформатные таблицы или графики и т.п.)

*Промежуточные отчеты могут оформляться в любой приемлемой среде, позволяющей эффективный обмен версиями документов между командой и преподавателями. Предпочтительным является формат облачных документов, к которым можно предоставить доступ по ссылке. Допускаются форматы текстовых документов (MS Word, Google Documents или т.п.), документы в формате LaTex или т.п. (Overleaf и др.), документы формата online-notebook (R-notebook, Jupyter notebook и т.п. открытые в GitHub или т.п.). Возможны иные форматы по согласованию с преподавателями.*  
*Итоговый отчет должен быть скомпилирован / сохранен в формате PDF.  Конкретных требований к оформлению итогового отчета не предъявляется, однако оно должно соответствовать условию, что итоговый отчет является самостоятельным аналитическим отчетом, который должен быть понятным и хорошо читаемым потенциально незнакомому с темой и ходом исследования читателю.* 

---

# Критерии оценки

## Формула оценки

Проект оценивается по совокупности критериев качества как письменной части (отчета), так и устной презентации (защиты). Учитывается оценка индивидуального вклада участников группы в итоговую работу. Учитывается своевременное выполнение отдельных промежуточных заданий (следование календарю дедлайнов).
Оценка за проект определяется по формуле

$$О_{ПРОЕКТ} = 0,67\;\times\;О_{ОТЧЁТ} + 0,33\;\times\;О_{ЗАЩИТА} + О_{КОМАНДА} + О_{ДЕДЛАЙНЫ},$$
где

- $О_{ПРОЕКТ}$ - итоговая оценка за проект,

- $О_{ОТЧЁТ}$ - оценка за письменную часть работы (итоговый отчет),

- $О_{ЗАЩИТА}$ - оценка за устную защиту проекта,

- $О_{КОМАНДА}$ - бонус или штраф за вклад в командную работу,

- $О_{ДЕДЛАЙНЫ}$ - штраф за нарушение дедлайнов.

Вклад членов команды в групповую работу фиксируется в одной из последних версий отчета и подтверждается всей командой. В случае высоких усилий, позитивно повлиявших на качество результатов и/или эффективность командной работы, оценка $О_{КОМАНДА}$ может составить до +1 балла; в случае систематического неучастия члена команды в командной работе, оценка ОКОМАНДА может составить до -10 (минус 10) баллов по 10-балльной шкале.

Оценка $О_{ДЕДЛАЙНЫ}$ может принимать только значение 0 (если никакие дедлайны не были серьезно нарушены) или отрицательные значения до -10 (минус 10) баллов по 10-балльной шкале в случае систематического нарушения устанавливаемых дедлайнов, в результате которого становится трудно объективно оценить приложенные усилия и качество результатов работы команды. 

В целом, если нет отдельных замечаний к индивидуальным вкладам конкретных студентов, а также случаев нарушения дедлайнов группой, итоговый вариант отчета и защита проекта оцениваются в соответствие с критериями, представленными далее.

## Критерии оценки групповой эмпирической работы (“Проекта”)

### Отлично (8-10)

Хорошо структурированное аналитическое представление проектной работы в виде самостоятельного письменного аналитического отчета. Демонстрирует убедительные доказательства и обширные базовые знания. В групповом отчете ожидается, что все члены проектной группы внесут более или менее равный вклад, и каждый вклад явно основан на предыдущем. Индивидуальный вклад отдельных членов команды указывается непосредственно в отчете и подлежит проверке руководителем группы (членом команды, делегированным для выполнения работы на этапе создания команды). Ответы на уточняющие вопросы показывают хороший диапазон и глубину проведенного анализа и четкое понимание вопроса исследования.

### Хорошо (6-7)

Четко организованный анализ, свидетельствующий о хорошем общем знании вопроса исследования. Не более одной трети отдельных участников вносят значительно меньший вклад в конечный результат, чем другие члены команды. Должно быть доказательство того, что группа собралась для обсуждения темы и представляет результаты реальной совместной работы. Ключевые моменты и вопросы рассмотрены надлежащим образом, некоторые технические детали или важные комментарии могут отсутствовать.

### Удовлетворительно (4-5)

Использует очень простой подход к теме, используя в целом подходящий материал, но не уделяя должного внимания. Представление результатов проекта в значительной степени неструктурированно, и некоторые моменты не имеют отношения к теме. Знание темы ограничено, и могут быть доказательства фундаментального непонимания. В групповой презентации большая часть работы выполняется одним или двумя студентами, и индивидуальные вклады не складываются.

### Неудовлетворительно (1-3)

Не может продемонстрировать какие-либо соответствующие знания и надлежащую организацию совместной работы.

### Отсутствует (0)

Нет свидетельств того, что была предпринята попытка приступить к выполнению задания.

---

# *ВиО*

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

[Назад на страницу курса](../ecox22.html)
