---
title: "Разведанализ данных и черновик полного отчета"
subtitle: "Проектное задание по курсу Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Обзор этапа

### **Цель:** предоставить черновик полного отчета с законченным введением и формулировкой вопроса, описанием и результатами разведывательного анализа данных, а также с набросками остальных частей полного отчета

### **Дедлайн:** 20:00 (Мск) 12.11

---

# Первый черновик полного отчета

На этом этапе вам необходимо предоставить первый черновик итогового отчета. Прежде всего для этого нужно доработать моменты, которые требовали доработки по результатам предыдущих этапов (постановка вопроса, выбор и сбор данных, уточнение вопроса).

Далее требуется добавить разведанализ данных и предварительную формулировку модели, а также элементы остальных разделов итогового отчета (хотя бы на уровне заголовков элементарных формулировок).

Все имеющиеся к окончанию этого этапа наработки необходимо объединить в один черновик итогового отчета. Рекомендации по структуре итогового отчета можно посмотреть в [полном задании на проект](project_task.html). Также далее в этом задании даны рекомендации на основе частых ошибок в подготовке отчета.

---

# Что нужно сделать?

1. Обсудить командой состояние вашего исследовательского вопроса - утвержден ли вопрос преподавателями, какие рекомендации вам дали для уточнения или модификации вопроса.

2. То же самое касательно выбора данных.

3. Провести разведанализ данных (подробнее далее).

4. Предварительно сформулировать модель и основную рабочую гипотезу (гипотезы). 

5. Коротко привести (хотя бы в виде заголовков или элементарных формулировок или плана действий) прочие разделы будущего итогового отчета.

6. Объединить все имеющиеся наработки в черновик отчета, следуя требованиям к его структуре (подробнее далее и в полном задании на проект). 

7. Сообщить преподавателям об изменениях в отчете. Дождаться комментариев и замечаний или утверждения черновика отчета и зачета на этом этапе.

8. Если у преподавателей есть комментарии и замечания, нужно вернуться к групповому обсуждению и устранить их, сообщить об изменениях преподавателям. 

---

# Как провести разведанализ данных?

**Конкретных требований к тому, что должно входить в разведанализ данных, нет.**

#### **Основное правило: результаты разведанализа данных должны помочь вам (и читателям отчета) понять, как именно эти данные помогут ответить на поставленный исследовательский вопрос.**

## Что может быть в разведанализе данных?

- Описательные статистики

- Базовые визуализации

- Классификации и опсиание грапповых статистик

- Анализ выбросов

- Анализ пропусков

- Критический анализ качества данных

- И пр.

### Чего категорически не может быть в разведанализе данных

**Категорически неприемлемы любые элементы из вышеперечисленных (или что-то подобное), если они не сопровождаются релевантными и уместными комментариями о том, как это вписывается в исследование.**

## Что может быть итогом разведанализа данных?

- Некоторые модификации вопроса (но небольшие). *Необходимо пояснить эти уточнения, обосновать с точки зрения логики, интуиции, теории, других исследований или т.п.*

- Чистка данных (от выбросов, напрмиер, или обработка пропусков). *В этом случае нужно обновить описание данных, скорректировав описание переменных, размера выборки и пр.*

- Предварительная формулировка модели (как синтес всех первых этапов: постановка вопроса + описание данных + разведка)

- И т.п. в той мере, насколько это вписывается в исследование.

---

# Еще раз об отчете: **Отчет $\neq$ лабораторный журнал**

Главное, помните, что *“Итоговый отчет представляет собой законченный и самостоятельный документ формата «Аналитический отчет о проделанной работе»...”* ([задание на проектную работу](project_task.html), раздел “Итоговый отчет”).

Даже черновик итогового отчета должен соответствовать формату отчёта. Документ должен читаться последовательно и относительно легко (подразумевается, что аудитория читателей - это люди, подкованные как минимум в основах экономики, работы с данными, эконометрике, чтении научной литературы).

В основном тексте отчета не должно быть фрагментов кода, большого количества графиков и таблиц, огромных графиков и таблиц и т.д. Код необходимо оформить отдельно в виде приложения или (даже лучше) онлайн приложения, в основном тексте стоит затем дать ссылку на него или по необходимости ссылаться на необходимые фрагменты этого приложения.

Аналогично стоит поступить с графиками, таблицами и прочими вспомогательными материалами. Все вспомогательные материалы, полученные в процессе работы, стоит оформить в виде приложений (очень большие - в виде онлайн-приложений) и поместить в соответствующие разделы отчета, а в основном тексте дать на них ссылку и по необходимости ссылаться на нужные фрагменты этих приложений.

Однако в основном тексте необходимо использовать минималистичные и предельно информативные таблицы, графики и т.д. Все они должны подкреплять те или иные аргументы и объяснения, которые необходимы для чтения отчета и понимания хода и результатов работы. Эти материалы могут быть компиляцией основных результатов, приводимых в приложениях, их сокращенными версиями или выжимками. Полные версии, на основании которых составлены материалы для основного текста, должны быть оформлены в приложениях с соответствующими ссылками на них.

---

# Когда дедлайн? 

Жесткий дедлайн: до 20:00 (Мск) 12 ноября (суббота). До этого времени преподаватели должны утвердить предоставленный черновик отчета. **Если у преподавателей останутся вопросы или нерешенные комментарии к постановке вопроса или выбору данных, дедлайн не засчитывается.**

---

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

[Назад к проектному заданию](project_task.html)

[Назад на страницу курса](../ecox22.html)
