---
title: "Регрессионный анализ и второй черновик полного отчета"
subtitle: "Проектное задание по курсу Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Обзор этапа

### **Цель:** предоставить второй черновик полного отчета с законченным введением и формулировкой вопроса, описанием и результатами разведывательного анализа данных, формулировкой моделей, результатами регрессионного анализа и проверки гипотез, а также с набросками остальных частей полного отчета, включая начало работы над анализом ограничений исследования и дискуссионной частью.


### **Дедлайн:** 20:00 (Мск) 03.12

---

# Второй черновик полного отчета

На этом этапе вам необходимо предоставить второй черновик итогового отчета. Прежде всего для этого нужно доработать моменты, которые требовали доработки по результатам предыдущих этапов (постановка вопроса, выбор и сбор данных, уточнение вопроса, разведанализ и описание данных, постановка модели).

Далее требуется добавить добавить в отчет результаты регрессионного анализа и проверки гипотез, начать работать над анализом ограничений исследования и дискуссионной частью.


Рекомендации по структуре итогового отчета можно посмотреть в [полном задании на проект](project_task.html). Также далее в этом задании даны рекомендации на основе частых ошибок в подготовке отчета.

---

# Что нужно сделать?

1. Обсудить командой состояние ваших данных и модели. Была ли одобрена модель модель преподавателями? Какие рекомендации вам дали по поводу моделей?

2. То же самое касательно разведанализ и качества данных, описания данных.

3. Провести регрессионный анализ и проверку гипотез (подробнее далее). 

4. Начать работать на анализом ограничений исследования и писать дискуссионную часть отчета.

5. Сообщить преподавателям об изменениях в отчете. Дождаться комментариев и замечаний или утверждения черновика отчета и зачета на этом этапе.

6. Если у преподавателей есть комментарии и замечания, нужно вернуться к групповому обсуждению и устранить их, сообщить об изменениях преподавателям. 

---

# Что важно сделать при проведении регрессионного анализа?

**Конкретных требований к тому, что должно входить в регрессионный анализ нет, т. к. многое зависит от специфики исследовательского вопроса**

#### **Основное правило: результаты регрессионного анализа должны помочь вам (и читателям отчета) понять, как именно он помогает ответить на поставленный исследовательский вопрос.**

## Что рекомендуется делать при регрессионном анализе и проверке гипотез?

- Оценка параметров при помощи МНК.

- Расчет робастных стандартных ошибок. 

- Представление результатов оценивания нескольких моделей в одной таблице. 

- Интерпретация результатов. 

- Проверка простых гипотез о коэффициентах

- Проверка сложных совместных гипотез о коэффициентах

- Проверка гипотез о предельных эффектах

- И пр.

### Чего категорически не может быть при проведении регрессионного анализа

- **Категорически неприемлемы любые элементы из вышеперечисленных (или что-то подобное), если они не сопровождаются релевантными и уместными комментариями о том, как это вписывается в исследование.**


## Что может быть итогом регрессионного анализа?

- Модификации модели и гипотез (но небольшие). *Необходимо пояснить эти уточнения, обосновать с точки зрения логики, интуиции, теории, других исследований или т.п.*

- Содержательная интерпретация результатов и обсуждение (в тексте) ограничений исследования.

- И т.п. в той мере, насколько это вписывается в исследование.

---

# Еще раз о регрессионном анализе и проверке гипотез

В своем исследовании ваши усилия должны быть направлены на ответ на поставленный исследовательский вопрос. Вы должны дать ответ на этот вопрос, но при этом понимать ограничения использования своих результатов. 

Но также не забывайте, что вы должны продемонстрировать в своей работе, что вы освоили навыки, преподаваемые в рамках курса "Эконометрика". 

Например, мы точно ожидаем, что: 

- Вы понимаете, что (экономическая) теория, (экономическая) интуиция важнее для модели, чем разведанализ и статистическая значимость. 

- Вы понимаете, что идеальных моделей не существует, поэтому ваша задача --- не сформулировать и оценить одну модель, а работать с несколькими альтернативными моделями и сравнивать результаты. 

- Вы умеете представлять результаты нескольких регрессий в одной таблице, а не по отдельности. 

- Вы умеете формулировать гипотезы в содержательной, модельной и нормальной формах и покажете это в отчете. 

- Вы умеете проверять гипотезы не только об отдельных коэффициентах, но и сложные совместные гипотезы и гипотезы о предельных эффектах. Поэтому, если вы еще это не сделали, предварительно еще раз подумайте о своих моделях и сформуулируйте их так, чтобы они предполагали возможность проверки таких гипотез. Если у вас возникают с этим трудности, не стесняйтесь спрашивать у преподавателей. 

- Вы понимаете, что такое угрозы внутренней и внешней валидности и можете выявить их для своего исследования. 


---

# Когда дедлайн? 

Жесткий дедлайн: до 20:00 (Мск) 3 декабря (суббота). До этого времени преподаватели должны утвердить предоставленный черновик отчета. **Если у преподавателей останутся вопросы или нерешенные комментарии дедлайн не засчитывается.**

---

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

[Назад к проектному заданию](project_task.html)

[Назад на страницу курса](../ecox22.html)