---
title: "Защита проектов"
subtitle: "Проектное задание по курсу Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Обзор этапа

### **Цель:** пройти публичную групповую защиту проекта в установленном формате.


### **Время защит:** 
- 17.12 с 15 до 19 часов 
- 20.12 с 15 до 19 часов

Оценки будут сообщены после окончания всех защит, т. е. после 20.12.

---

# Распределение по дням
Для записи на один из дней защиты, пожалуйста, обсудите командой свои предпочтения: какой день и время для вас наиболее желательны. Сообщите о своих приоритетах, заполнив [форму](https://docs.google.com/forms/d/e/1FAIpQLSf3meQ1_Ykyix7I50NUqk-krEIHT9tQe9Q7hvHeuRVVszfz4w/viewform?usp=sf_link).

Форма будет открыта до 20:00 пятницы 16.12! После закрытия формы будет произведено распределение команд по дням в соответствии с приоритетами и нашими возможностями принять защиту у определенного количества команд в определенный день. Мы зафиксируем и сообщим расписание с конкретным днем и временем защиты для каждой команды.

Расписание защит проектов будет доступно по [ссылке](https://docs.google.com/spreadsheets/d/1zBpU7pqoFo4D2KKd0h6vE4wg5_JaOQaX4lT5pXWPvJ8/edit?usp=sharing).
В расписании будет время указано для каждой команды. Ссылки на онлайн встречи будут добавлены позднее в тот же файл с расписанием.

Внимание! Найдите номер свой команды в расписании. Необходимо присоединиться немного заранее (пару минут) полным составом команды и уложиться полностью в отведенный вашей команде слот. В случае опоздания время опоздания вычитаем из времени выступления.

---

# Защита проекта

## Формат защиты
- онлайн
- устный доклад с презентацией в течение 7 минут
- вопросы комиссии и ответы в течение 7 минут

## Доклад и презентация, ответы на вопросы
- на защите необходимо присутствовать всей команде (с включенными камерами)
- доклад делает 1-2 человека от команды
- на вопросы всей команде могут отвечать все/любые члены команды, комиссия также может задать вопрос любому члену команды и требовать ответ от него/неё
- присутствовать на защите других команд нет необходимости
