---
title: "Сбор команды для выполнения Проекта"
subtitle: "Проектное задание по курсу Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Обзор этапа

### **Цель:** самоорганизоваться в команду для выполнения проектной работы по курсу и согласовать состав с преподавателями

### **Дедлайн:** 20:00 (Мск) 25.09

---

## Что необходимо знать о проектной команде?

- Команда формируется один раз и остается неизменной в течение всего курса

- Размер команды строго ограничен: от 5 до 8 человек

- Каждый студент потока должен состоять ровно в одной проектной группе

- Каждая команда выбирает одного лидера группы из своего состава

## Что нужно сделать, чтобы выполнить этот этап задания?

1. Самоорганизоваться и собраться проектной группой допустимого размера

2. Выбрать лидера группы. Процедура выбора лидера - на усмотрение группы.

3. Лидер группы отчитывается [Дмитрию Сергеевичу Терещенко в телеграм @dmitriy_te](t.me/dmitriy_te) о собранной группе, нужно написать:

  - свое имя, академическую группу и email,
  
  - состав команды - группы и полностью имена
  
4. Д. С. Терещенко должен подтвердить лидеру группы, что состав команды утвержден.

## Когда дедлайн? 

Жесткий дедлайн: до 20:00 (Мск) 25 сентября (воскресенье). До этого времени состав команды должен быть утвержден. Лучше связаться заранее, чтобы была возможность внести исправления, если потребуется.

## Прочее

### Каковы функции лидера группы?

Вся коммуникация с преподавателями по поводу групповой работы - только через лидера группы от имени группы. 
Организация внутригрупповой коммуникации - задача лидера группы.

Распределение ролей, задач, конкретных заданий на разных этапах работы и т.п. остается на усмотрение группы. Это можно быть функцией лидера, а может решаться на основе какой-нибудь процедур агрегации мнений.

---

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

[Назад к проектному заданию](project_task.html)

[Назад на страницу курса](../ecox22.html)
