---
title: "Отчёты по летучкам"
subtitle: "Эконометрика"
output:  
  html_document:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Место летучек в курсе

Короткие проверочные работы (*aka* "Летучки") - одна из трёх форм текущего контроля на курсе. Доля всех летучек в итоговой оценке составляет 12%. Летучки проводятся во время лекций и длятся до 10 минут, в течение которых каждому студенту нужно дать ответы на ряд вопросов на интерактивной платформе [Wooclap](https://www.wooclap.com), следуя объявленным правилам. 

Цель летучек: стимулировать посещение лекций и своевременной повторение основных моментов материала.

</br>

[Назад на страницу курса](../ecox22.html)

</br>

---

# Подготовка к летучкам

Для подготовки к летучкам необходимо пользоваться:

- материалами лекций и семинарских занятий,

- материалами для самостоятельного изучения,

- учебником,

- пробными тестами.

</br>

Перед каждой летучкой (за 1-2 дня до проведения) предоставляется пробный тест на странице [wooclap.com/EX22TRAIN](https://app.wooclap.com/EX22TRAIN?from=event-page).

**Настоятельно рекоменджуется проходить тест заранее и задавать вопросы в чате!**

</br>

---

# Формат и оценки 

Оценки за летучки (и за все прочее) можно посмотреть в [общем файле с оценками](https://docs.google.com/spreadsheets/d/1vf9O4QXcfXI60cl--JU3ThF4EwgbCZXqMG1N0gAoKaY/edit?usp=sharing).

Каждая летучка включает 10-12 тестовых вопросов или коротких задач, на каждый из которых всегда есть ровно один правильный ответ. Оценка за летучку всегда определяется по формуле

$$О_{ЛЕТУЧКА}=\min(10;\;количество\;правильных\;ответов).$$

</br>

---

# Отчёты и ответы

- [Летучка не на оценку 09.09](https://drive.google.com/file/d/1OQjOGU8euMd8ea97ZfqaZwjMRaZxRGg-/view?usp=sharing)

- [Летучка 1 23.09](https://drive.google.com/file/d/1yvHi7LnHDkAT2G4Va0LMj3-WZRZ4UH-V/view?usp=sharing)

- [Летучка 2 30.09](https://drive.google.com/file/d/1iEGXzau4BBTyLDH2yZ-NvvQR7OorT1lp/view?usp=sharing)

</br>

---

# *ВиО*

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

---

[Назад на страницу курса](../ecox22.html)
