---
title: "Раздел 1. Введение в курс."
subtitle: "Эконометрика"
output:  
  html_document:  
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Введение

Это вводный раздел курса "Эконометрика". Здесь вы найдёте основные сопроводительные инструкции к курсу и материалы для самостоятельного изучения на первые две недели семестра.

[Назад на страницу курса](../ecox22.html)

## Что такое эконометрика?
<iframe src="https://www.youtube.com/embed/N9QmG46bQRs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

---

# Связь

Для текушей связи мы используем Телеграм. Пожалуйста, присоединяйтесь к общему чату и каналу. В чате можно задать любые вопросы по курсу и получить поддержку. Также в канал и чат будут транслироваться важные новости о ходе курса, информация о занятиях, оценках, новых материалах и пр. *Оставайтесь на связи!*

- [Общий чат](https://t.me/+0kRsodLpmzRmZjEy)

- [Канал "Важное"](https://t.me/+EEU2C0MI4oYwMzE6)

---

# Материалы
## Организация курса

<iframe src="https://www.youtube.com/embed/0yMaLilPJSs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Краткая программа курса

  - [Разделы курса, литература](https://docs.google.com/document/d/1cGaK7pvG61RI30DmtLCJt3qhrz1ExxO7hfP_9yeRBtU/edit?usp=sharing)
  
  - [Формула и криетрии оценки](https://docs.google.com/document/d/15Ccydaa_jH7cDcTY3i0-kO-YzLyn5TCkXpLY5jxLBFc/edit?usp=sharing)

- [Инструкции по регистрации в Wooclap](https://docs.google.com/document/d/14Iq99s6JZkxJ0v8XJwFprWJGOqDh4MnzOGAnbvkUyQ0/edit?usp=sharing)

## Учебники

- [Основной учебник (на русском)](https://drive.google.com/file/d/1PtKqrh0cXjDLZy4rMeLwN2uH5lvlt7P-/view?usp=sharing)

- [Основной учебник (English)](https://drive.google.com/file/d/1_2CIz-DHImH2K0NT-A6wYtzXhpD1f3zW/view?usp=sharing)

- [Прочее](https://drive.google.com/drive/folders/16cJVmyi_MnzMTPcHWUDhigpaCdBQkm0g?usp=sharing)

## Для самостоятельного изучения

<iframe src="https://www.youtube.com/embed/arDaLS74Lx0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Вводный раздел курса посвящён основным организационным вопросам, но в первую очередь - повторению необходимых основ теории вероятностей и математической статистики, без которых успешное освоение эконометрики без преувеличения невозможно.

Далее приведен список материалов для самостоятельного изучения и краткая инструкция, которая поможет в них сориентироваться.

К первым семинарским занятиям мы ожидаем, что вы повторите необходимые основы теории вероятностей: случайные исходы и события, случайные величины и распределения, дискретное распределение, непрерывное распределение, моменты случайных величин, математическое ожидание, дисперсия, совместное и условное распределения случайных величин, условное математическое ожидание, закон повторного математического ожидания, последовательности случайных величин, закон больших чисел, нормальное распределение, центральная предельная теорема. 

К семинарам второй недели от вас ожидается повторение необходимых разделов математической статистики: данные и выборки, случайная выборка, различия между выборкой и генеральной совокупностью (популяцией), параметры и оценки, оценки, как случайные величины, свойства оценок, основы проверки гипотез, виды статистических гипотез, некоторые варианты статистических критериев, схема применения критерия согласия, доверительные интервалы.

 - [Инструктаж и список материалов для самостоятельного изучения](https://docs.google.com/document/d/1IbdmEnVDgCYQEMa4c-w58YiM0O12G4PvVYg-dJUEmc8/edit?usp=sharing)

 - Вероятностный параметрический подход
 
<iframe src="https://www.youtube.com/embed/HHBzpmOWQpc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

 - Система обозначений в курсе
 
<iframe src="https://www.youtube.com/embed/yF_0E3uw6Ek" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

## Лекция 1 - 02/09/2022

*Введение в курс. Что такое и чем занимается эконометрика. Эконометрические вопросы. Вероятностный и параметрический подход. Простая "модель". Математические ожидания. Условные математические ожидания. Закон итеративных (повторяющихся) математических ожиданий.*

- [Слайды](lec01_intro_lime.html)

- Запись лекции

<iframe src="https://www.youtube.com/embed/Vkrp_HY6zrs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

- **Дополнительно: невошедшее в лекцию.** Закон итеративных математических ожиданий.

<iframe src="https://www.youtube.com/embed/5JWiQBsblvc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

## Семинар 1 - 06/09/2022

*Повторение основ теории вероятностей. Введение в работу с данными в R. Решение задач, разбор простого эмпирического упражнения с данными.*

- [Задание](sem01_prob_r.html)

- [Разбор эмпирической части](sem01_tutorial.html)

## Лекция 2 - 09/09/2022

*Популяционные характеристики эконометрических моделей и их выборочные аналоги. Метод аналогии. Оценки параметров, как случайные величины. Несмещенность оценки.*

- [Слайды](lec02_samples_analogy_validity.html)

- [Результаты летучки](https://drive.google.com/file/d/1OQjOGU8euMd8ea97ZfqaZwjMRaZxRGg-/view?usp=sharing)

- Запись лекции

<iframe src="https://www.youtube.com/embed/fRUYCjT_Cnc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Дополнительно. 

*Из материалов прошлого года:* классификация подходов, параметрические регрессионные модели, модель "регрессия на константу". **Обратите внимание на пример простой модели в качестве альтертативы простого примера про разрыв в зарплате мужчин и женщин, разобранный на лекции.**

<iframe src="https://www.youtube.com/embed/YaatAkBSYiM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


---

# *ВиО*

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

---
[Назад на страницу курса](../ecox22.html)
