---
title: "Раздел 2. Парная линейная регрессия."
subtitle: "Эконометрика"
output:  
  html_document:  
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Введение

Наш основной инструмент анализа в эконометрике - регрессионные модели. Первое время мы сосредоточимся на более простом с технической стороны случае - парной регрессии. Рассмотрим в деталях теоретическую сторону модели, принцип получения оценок, их свойства и использование для анализа (Неделя 3). Поговорим об ограничениях модели парной регрессии и необходимости перехода к множественной модели.

[Назад на страницу курса](../ecox22.html)

---

# Тема 4. Модель регрессии - введение

## Обязательно

<iframe src="https://www.youtube.com/embed/KOPlO00ZN_U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Дополнительно

- HE, Глава 2

---

# Тема 5. Модель парной линейной регрессии

## Обязательно

### Чтение

- SW: вся глава 4, не упустите приложения после упражнений!

- SW: вся глава 5

</br>

### Модель парной линейной регрессии в деталях

<iframe src="https://www.youtube.com/embed/Gni_FfQso4o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### То же, укороченная версия

<iframe src="https://www.youtube.com/embed/MLD6DGmKYc8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### Лекция 3

*только запись, слайдов нет*

<iframe src="https://www.youtube.com/embed/piBx6-4NKjo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### Семинар 3. *Парная линейная регрессия*

- [**Задание**](sem03_pair_reg.html)

</br>

### *Парная линейная регрессия: эмпирический пример*

**Материал обязателен к просмотру перед 4 лекцией и семинарами.** 

*Разбор кода не считается разбором материала!*

<iframe src="https://www.youtube.com/embed/8zcoGypRMcw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- [**Код из примера**](teeth_example.R)
  
- [**Альтернативный код**](example_teeth.html)

</br>

## Дополнительно

- HE: 3.4, 3.5, 3.7, 4.1-4.4

</br>

---

# Переходная тема: Валидность статистических исследований

<iframe src="https://www.youtube.com/embed/E65ChI1yiPQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### Семинар 4. *Парная регрессия: проверка гипотез и доверительные интервалы. Валидность статистических исследований*

- [**Задание**](sem04_pair_reg.html)

</br>

---

# Дополнительно ко всей теме

## Чтение

- SW: Глава 3, приложения 3.2 и 3.3 (в конце главы)

- W: Глава 2

- HS: 16.1-2, 17.1

- MOOC-1: неделя 1

- MOOC-2: неделя 3

- MOOC-3: неделя 2

## Алгебра парной линейной регрессии - свойства оценок

### Состоятельность оценок МНК (часть 1)

<iframe src="https://www.youtube.com/embed/oarN30FJdCg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Состоятельность оценок МНК (часть 2)

<iframe src="https://www.youtube.com/embed/2x0MIq_RKMw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### Несмещенность оценок МНК

<iframe src="https://www.youtube.com/embed/qM70fy637Io" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### Асимптотическое распределение оценок МНК

<iframe src="https://www.youtube.com/embed/Pyid6rj_Ywo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Стандартные ошибки оценок МНК
  
<iframe src="https://www.youtube.com/embed/vU1HDB5albc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Зачем нам асимптотическое распределение?
  
<iframe src="https://www.youtube.com/embed/Cp8mnaDHl_M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

---

### [Рекомендуемые задачи для самоконтроля](sec2_self_control01.html)

</br>

---

# *ВиО*

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

---
[Назад на страницу курса](../ecox22.html)
