---
title: "Раздел 3. Алгебра МНК в ММЛР."
subtitle: "Эконометрика"
output:  
  html_document:  
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Введение

Раздел, касающийся теории и практики оценивания и анализа свойств оценок главного инструмента регрессионного анализа в эконометрике - **модели множественной линейной регрессии** (*aka* **ММЛР**).

### Где я?

<iframe src="https://www.youtube.com/embed/kI9ZTCBHYCw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### Проблема пропущенных переменных

<iframe src="https://www.youtube.com/embed/G9snb5U4ttw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

<iframe src="https://www.youtube.com/embed/1Uj2-0xzXyM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

[Назад на страницу курса](../ecox22.html)

</br>

---

# Тема 6. Основы ММЛР: запись и постановка, алгебра МНК

## Обязательно

### Постановка ММЛР и формы записи

<iframe src="https://www.youtube.com/embed/uszFRExmfVY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

### Алгебра МНК в ММЛР

#### Оценки МНК парамтеров ММЛР

*Следующие три ролика в колоссальном количестве деталей раскрывают технику выведения оценок методом наименьших квадратов в модели множественной линейной регрессии. Если вы уверенно себя чувствуете в работе с матрицами и вам понравилась матричная форма записи ММЛР из предыдущего ролика, то достаточно разобрать сокращенную версию выведения (ролик три).*

</br>

**Очень детально: от популяционной задачи к оценкам через скалярнужю запись**

<iframe src="https://www.youtube.com/embed/32tYtUsQEb0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

**Короче, меньше деталей, не такая страшная алгебра**

<iframe src="https://www.youtube.com/embed/7XOUeEsLHzQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

**В матричной форме: еще короче, но алгебра пострашнее**

<iframe src="https://www.youtube.com/embed/uP-fQQoGq5I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

#### Свойства оценок МНК параметров ММЛР

*Без преувеличения, центральный раздел темы про теорию модели линейной регрессии - свойства оценок МНК в ММЛР. Первые два ролика являются детальным подведением к третьему, в котором выводится асимптотическое распределение оценок МНК - объект колоссальной важности для эмпирической работы и понимания, на чём держится проверка гипотез, связанных с параметрами в моделях (не только в ММЛР).*

<iframe src="https://www.youtube.com/embed/JZK2r9IMQcc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

<iframe src="https://www.youtube.com/embed/2vHTt1wmRkM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

<iframe src="https://www.youtube.com/embed/7_yXXYs74tw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

#### Стандартные ошибки оценок МНК параметров ММЛР

*Возможно, слищком сложный ролик... И длинный. Если вы еще не разобрались, кто такие стандартные ошибки - вам сюда.*

<iframe src="https://www.youtube.com/embed/OTt4N6f_t7Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

## Дополнительно 

### Парная регрессия, как частный случай ММЛР

<iframe src="https://www.youtube.com/embed/q0_REl2J6U8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Лекция 5

Разбор летучек по введению в регрессию и парной регрессии

<iframe src="https://www.youtube.com/embed/jFSOHebprKw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

---

# Эмпирические примеры

## Пространственная ценовая конкуренция на AirBnB (лекция 2021)

<iframe src="https://www.youtube.com/embed/mabuNaYluqw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

## Риск инфекционного заражения в больнице (материал 2021)

### [Код из разбора](hospitaldata.R)

<iframe src="https://www.youtube.com/embed/0Rqa5z6rezw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</br>

---

### Семинар 5. *Модель множественной линейной регрессии. Проблема пропущенных переменных. Контрольные переменные*

- [**Задание**](sem05_mult_reg.html)

- [**Разбор эмпирической части**](sem05_mult_reg_tutorial.html)

---

### Семинар 6. *ММЛР. Категориальные переменные и дамми-переменные. Идентификация и мультиколлинеарность*

- [**Задание**](sem06_dum_multicol.html)


# *ВиО*

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)

---

[Назад на страницу курса](../ecox22.html)
