---
title: "Раздел 5. Регрессионный анализ: дополнительные темы"
subtitle: "Эконометрика"
output:  
  html_document:  
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

# Тема 9. Инструментальные переменные

## Мотивация
Часто говорят, что именно работа с инструментальными переменными - это та грань, которая отличает эконометрику от статистики. Есть множество контекстов, в которых возникает необходимость использования инструментальных переменных, но главный --- это проблема эндогенности, т.е. скоррелированность регрессоров с ошибкой в потенциальной регрессионной модели, из-за чего модель перестает быть ММЛР, а привычные для нас МНК оценки теряют необходимые свойства и смысл. 

В ближайшие несколько недель мы будем рассматривать так называемую IV-регрессию (“ай-ви регрессию” или регрессию с инструментальными переменными). Мы начнем с простого случая, который будет аналогом парной модели в изучении ММЛР. Затем перейдем к множественным моделям, обсуждении их популяционных свойств, применению методов оценки, выведению и использованию свойств оценок. Основной метод оценивания, который мы будем рассматривать --- это двухшаговый метод наименьших квадратов.


## Лекция 9
Эндогенность и инструментальные переменные (1)

- [Слайды](lect09_IV.pdf)


## Обязательное чтение

- SW, глава 12


## Обязательные видео

### Эндогенность и инструментальные переменные
Напоминание о сущности проблемы эндогенности. Источники проблемы эндогенности: пропущенные переменные, одновременность, ошибки измерения. Возможные решения. Инстурментальные переменные (введение).

- [Ссылка на видео](https://drive.google.com/file/d/1BzQk1kP8gSODQ3fMNTvx2XecY5vEBig1/view)

### Двухшаговый метод наименьших квадратов (парный случай)
Модель с инструментальными переменными и двух-шаговый метод наименьших квадратов. Парный-парный случай и свойства оценок. Общий случай и выведение оценок 2шМНК.

- [Ссылка на видео](https://drive.google.com/file/d/10BEKLUZSiv60ePQsQ4TkE4LwAhvPmWop/view)

## Семинар 11
Инструментальные переменные (1)

- [Задание](sem11_IV.html)

## Лекция 10
Эндогенность и инструментальные переменные (2)

- [Слайды](lect10_IV2.pdf)

## Еще одно обязательное видео
Обоснование свойств оценок 2шМНК. Состоятельность и асимптотическое распределение. Оценка асимптотического распределения. Проверка гипотез.

- [Ссылка на видео](https://drive.google.com/file/d/1VeT0lL7CM2kar0ragGs6EYoFEIcN6wR5/view)

## Семинар 12
Инструментальные переменные (2)

- [Задание](sem12_IV2.html)


# Тема 10. Модели бинарного выбора

## Обязательное чтение
- SW, глава 11

## Дополнительное чтение
- HE, chapter 25

## Лекция 11
Модели бинарного выбора (1)

- [Слайды](lect11_bin.pdf)

## Семинар 13
Модели бинарного выбора (1)

- [Задание](sem13_bin.html)

## Лекция 12
Модели бинарного выбора (2)

- [Слайды](lect12_bin2.pdf)

## Семинар 13
Модели бинарного выбора (2)

- [Задание](sem14_bin2.html)