---
title: "Эконометрика"
subtitle: "Нотация"
author: "В. Н. Пырлик"
date: "Август 2022"
output:
  xaringan::moon_reader:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "16:9"
---
class: animated, zoomIn
## Вероятностный параметрический подход

- Экономические переменные и данные - **случайные величины**

- Зависимости между переменными описываются **моделями с параметрами**

- Зависимости и параметры - **неслучайные, детерминированные**

---
class: animated, zoomIn
## План

- Главное правило

- Основные обозначения и некоторые правила

---
class: section, animated, zoomIn
### *Главное Правило*

</br>

## **Внимательно читаем описание**
### **и не игнорируем контекст**

---
class: section, animated, fadeIn
### Нотация (0) **Все "правила" далее стоит читать с припиской**
</br>
## **"как правило..."**
### или
## **"...если это не противоречит здравому смыслу / контексту"**

---
class: animated, fadeIn
### Нотация (1)
## Случайные величины обозначаются латинскими буквами

$y,\;x,\;z,\;...$ - случайные величины

--

## Если с.в. - вектор (матрица), то буквы становятся заглавными

$Y, \; X$ - случайные векторы (матрицы)

--

### Тогда малыми буквами могут быть как значения с.в., </br> так и отдельные элементы векторов...

---
class: animated, fadeIn
### Нотация (2)
## Параметры моделей обозначаются малыми греческими буквами

$\beta_o,\;\beta_1$ - параметры модели, константы, не-случайные величины

---
class: animated, fadeIn
### .rb[Нотация (3)]
## Разница между популяционными величинами и наблюдаемыми,</br>а также между неизвестными параметрами и их оценками

*Часто мы имеем дело с моделями, в которых встречаются ненаблюдаемые величины, а параметры не являются известными. Мы используем наблюдаемые данные, чтобы узнать что-то о неизвестной нам части реальности...*

--

## Оценки параметров обозначаются теми же буквами, но в "шапках"

$\hat\beta_o$ - оценка параметра $\beta_o$

--

.rb[!] **Оценки параметров - это случайные величины.**

---
class: animated, fadeIn
### Нотация (4)
*Исключение из различий между латинскими и греческими буквами*

## Обозначения распределений могут быть какаими попало

--

$N(0,1)$ - стандартное нормальное распределение,</br> $\chi^2_k$ - хи-квадрат распределение

--

.rb[!] **и даже их параметры иногда обозначаются как попало**

---
class: animated, fadeIn
### Нотация (5)
## Векторы и матрицы

- все векторы - векторы-столбцы .right[.rmk[даже без приписки "как правило"]]

--

- в матрицах всегда индексация - "строка-столбец"

--

- **следите за размерностями матриц**

--

- любой вектор - матрица с одним столбцом

- любой скаляр - вектор из 1 элемента (матрица 1-на-1)

---
class: animated, fadeIn
### Нотация (6)
## Некоторые часто встречающиеся обозначения (1)

- $x\;\sim\;F$ - с.в. ... *имеет распределение* ...

- $\mathbb{E}x$, $Var[x]$ - матожидание, дисперсия с.в. $x$

- $\mathbb{E}[x|y]$ - матожидание с.в. $x$ условное по $y$

- $cov(x,y)$ - ковариация между с.в. $x$ и $y$

- $corr(x,y)$ - коэффициент корреляции между с.в. $x$ и $y$

---
class: animated, fadeIn
### Нотация (6)
## Некоторые часто встречающиеся обозначения (2)

- $\text{i.i.d.}$, $\text{iid}$ - независимые и одинаково распределенные

- $\{x_i\}_{i=1,...n}\sim iid$ - случайная выборка размера $n$

- $\bar{x}$ - выборочное среднее, $\bar x = n^{-1}\sum_{i=1}^n x_i$

- $\xrightarrow{p}$, $\xrightarrow{d}$ - "сходится по вероятности", "сходится по распределению"

- $\text{plim}$, $\text{dlim}$ - пределы по вероятности и по распределению

---
class: section, animated, zoomIn
### *Главное Правило*

</br>

## **Внимательно читаем описание**
### **и не игнорируем контекст**

---
class: section, animated, zoomIn
## Спасибо!


