---
title: "Эконометрика"
subtitle: "Максимально коротко о"
author: "В. Н. Пырлик"
date: "Август 2022"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "16:9"
---
class: animated, fadeIn
## План

- Максимально коротко об эконометрике

  - Определения эконометрики
  
  - Теоретическая и прикладная эконометрика
  
  - Что же мы изучаем?

---
class: section, animated, zoomIn
## Эконометрика - это ...

---
class: animated, fadeIn
### В широком смысле
# *эконометрика - это*

## наука и искусство использования экономической теории и статистических методов для анализа экономических данных.

.right[*SW, Глава 1*]

---
class: animated, fadeIn
# Эконометрика - это .rb[не только]

... *экономическая статистика*,

... *экономическая теория*, или

... *применение математики в экономике*.

--

# Эконометрика - это объединение этих трёх аспектов

---
class: animated, fadeIn
# Теоретическая и прикладная эконометрика

## Теоретическая эконометрика (*aka* эконометрическая теория)

... *рассматрвиает развитие эконометрического инструментария и изучает свойства эконометрических методов.*

--

## Прикладная экономтерика

... *посвящена разработке количественных экономических моделей и применению к ним эконометрических методов с целью изучения экономических данных.*

.right[*HE, Chapter 1*]

---
class: animated, fadeIn
# Теоретическая и прикладная эконометрика

## Теоретическая эконометрика .gb[~ 20%*]

... *рассматрвиает развитие эконометрического инструментария и изучает свойства эконометрических методов.*

## Прикладная экономтерика .gb[~ 80%*]

... *посвящена разработке количественных экономических моделей и применению к ним эконометрических методов с целью изучения экономических данных.*

.gb[*: в нашем курсе]

---
class: section, animated, zoomIn
## Спасибо!


