---
title: "Семинар 9. Задание."
output:  
  html_document:  
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
mainfont: Liberation Serif
monofont: Liberation Mono
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Часть 1. Обсуждение модели

Ваша задача --- исследовать взаимосвязь между результативностью баскетболистов и их семейным положением. 


## Исследовательский вопрос

1. Сформулируйте исследовательский вопрос.

2. Сформулируйте исследовательскую гипотезу.

3. Обсудите экономический механизм, который бы ее объяснял.  


## Модель парной линейной регрессии

1. Выпишите модели парной линейной регрессии, которые подходят для описания изучаемых взаимосвязей. 

2. Обсудите проблему пропущенных переменных. К каким последствиям она может привести?

## ММЛР

1. Обсудите, какие контрольные переменные необходимо включить в модель для решения проблемы пропущенных переменных.

2. Выпишите ММЛР. 

3. Выпишите и обсудите предпосылки модели. 

4. Обсудите угрозы внутренней и внешней валидности исследования. 

## Нелинейные эффекты в ММЛР

### Полиномы

1. Обсудите, может ли существовать квадратичная зависимость результативности от опыта игрока. Добавьте квадрат этой переменной в модель. 

2. Опишите в деталях стратегию проверки значимости эффекта этого регрессора ("в деталях" означает довести до выражений формул необходимых статистик, обсудить варианты интерпретации результатов тестов).

### Перекрестные эффекты

1. Добавьте в модель взаимодействие семейного положения с опытом игрока, а также квадратом опыта. Обсудите, почему это может иметь смысл. 

2. Опишите в деталях стратегию проверки совместной значимости коэффициентов, относящихся к семейному положению ("в деталях" означает довести до выражений формул необходимых статистик, обсудить варианты интерпретации результатов тестов). 

3. Опишите в деталях стратегию проверки значимости эффекта семейного положения в завимиости от опыта ("в деталях" означает довести до выражений формул необходимых статистик, обсудить варианты интерпретации результатов тестов). Обсудите, в чем приницпиальное отличие этой проверки от проверки из предыдущего пункта.


# Часть 2. Эмпирическая оценка

## Загрузка пакетов

Не забудьте загрузить необходимые пакеты.

## Набор данных

На этом семинаре мы работаем с данными ["nbasal"](https://www.rdocumentation.org/packages/wooldridge/versions/1.4-2/topics/nbasal). Фрагмент данных можно загрузить, используя встроенный набор данных пакета [wooldridge](https://www.rdocumentation.org/packages/wooldridge/versions/1.4-2).

Загрузите и изучите загруженные данные. Обсудите, какие переменные лучше всего подходят для ответа на поставленный исследовательский вопрос.

## Оценка

Оцените модели и проверьте гипотезы, которые обсуждались в предыдущей части, используя возможности R.