---
title: "Семинар 11. Задание."
output:  
  html_document:  
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: ../extra.css
mainfont: Liberation Serif
monofont: Liberation Mono
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Часть 1. Упражнения и вопросы

## SW, глава 12, вопрос 12.1
Каким образом (положительно или отрицательно) $ln(P_i^{butter})$ коррелирует с $u_i$ в регрессионной модели спроса, представленной уравнением (12.3)? Если оценка проводится с помощью МНК, то можно ли ожидать, что оценка $\hat \beta_1$ будет больше или меньше своего истинного значения $\beta_1$. Поясните свой ответ.

## SW, глава 12, вопрос 12.3
В работе Левитта (Levitt, 1996) изучалось влияние количества заключенных на 100 тыс. человек населения на уровень преступности. Автором в качестве инструментальной переменной рассматривалось количество адвокатов на душу населения. Является ли этот инструмент релевантным? Является ли он экзогенным? Является ли инструмент допустимым?

## HE, chapter 12, ex. 12.1
\[ y_i = \beta_0 + \beta_1 x_i + u_i \]

\[ IV: z_i = \{0, 1 \} \]

Find a simple expression for the IV estimator in this context.

## SW, глава 12, упражнение 12.2
Рассмотрим модель регрессии с одним регрессором: \( y_i = \beta_0 + \beta_1 x_i + u_i \). Предположим, что все предположения из вставки "Основные понятия 4.3" выполнены.

a. Покажите, что \(x_i\) является допустимым инструментом. То есть покажите, что выполнено условие \(z_i = x_i\) из вставки "Основные понятия 12.3".

b. Покажите, что при таком выборе \(z_i\) предположения модели регрессии с инструментальными переменными из вставки "Основные понятия 12.3" выполняются.

c. Покажите, что IV-оценки, построенные с помощью данного инструмента, идентичны МНК-оценкам.

## SW, глава 12, упражнение 12.4
Рассмотрим 2МНК-оценку с единственной включенной эндогенной переменной и единственным инструментом. Тогда предсказанное значение, полученное на основе регрессии, оцененной на первом шаге, равно \(\hat x_i = \hat \pi_0 + \hat \pi_1 z_i\). Используя определения выборочных дисперсии и ковариации, покажите, что \(s_{\hat x y} = \hat \pi_1 s_{zy}\) и \(s^2_{\hat x} = \hat \pi_1^2 s_z^2\). Используйте этот результат, чтобы дополнить выкладки в приложении 12.2 для вывода формулы (12.4).


# Часть 2. Эмпирический пример

Ваша задача --- исследовать взаимосвязь между экономическим развитием и институтами. 

## Исследовательский вопрос

1. Сформулируйте исследовательский вопрос.

2. Сформулируйте исследовательскую гипотезу.

3. Обсудите экономический механизм, который бы ее объяснял.  


## Модель

1. Обсудите модель парной линейной регрессии, которая подходит для описания изучаемых взаимосвязей. 

2. Обсудите проблему эндогенности. К каким последствиям она может привести?

3. Обсудите, какие инструментальные переменные необходимо включить в модель для решения проблемы эндогенности.


## Загрузка пакетов

Не забудьте загрузить необходимые пакеты.


## Набор данных

На этом семинаре мы работаем с материалами статьи **Acemoglu, D., Johnson, S., & Robinson, J. A. (2001). The colonial origins of comparative development: An empirical investigation. American economic review, 91(5), 1369-1401**. Статья доступна по [ссылке](https://www.aeaweb.org/articles?id=10.1257/aer.91.5.1369).

Обычно хорошие статьи являются *воспроизводимыми*, т. е. их результаты при желании можно повторить. Так и в этой статьи данные и код доступны [онлайн](https://www.openicpsr.org/openicpsr/project/112564/version/V1/view). Мы же сегодня будет использовать похожие данные, которые можно скачать по [ссылке](AJR2001.txt) в формате .txt.

Загрузите и изучите данные. Обсудите, какие переменные лучше всего подходят для ответа на поставленный исследовательский вопрос.

<details>
  <summary>Описание переменных</summary>
| Name             | Label                                                     |
|------------------|-----------------------------------------------------------|
| longname         | full country name                                         |
| shortnam         | 3 letter country name                                     |
| logmort0         | Original Log Settler Mortality                            |
| risk             | Exp Risk                                                  |
| loggdp           | Log GDP per capita (PPP) in 1995                          |
| campaign         | Original mortality from campaign                          |
| source0          | Country source of own m. rate                             |
| slave            | Data from forced labor                                    |
| latitude         | Absolute value of latitude                                |
| neoeuro          | 'New-Europes'(USA,CAN,AUS,NZL)                            |
| asia             | Asia                                                      |
| africa           | Africa                                                    |
| other            | 'Other' Cont (AUS, NZL, MLT)                              |
| edes1975         | Pop of Euro Descent, 1975                                 |
| campaignsj       | Ошибка:509                                                |
| campaignsj2      | Ошибка:509                                                |
| mortnaval1       | mortality using naval stations, method 1                  |
| logmortnaval1    | logr mortality using naval stations, method 1             |
| mortnaval2       | mortality using naval stations, method 2                  |
| logmortnaval2    | log mortality using naval stations, method 2              |
| mortjam          | mortality benchmarking to the Caribbean                   |
| logmortjam       | log mortality benchmarking to the Caribbean               |
| logmortcap250    | log mortality capped at 250                               |
| logmortjam250    | log mortality benchmarked to the Caribbean, capped at 250 |
| wandcafrica      | west and central Africa                                   |
| malfal94         | Falciparum malaria index 1994                             |
| wacacontested    | contested observations in west and central Africa         |
| mortnaval2250    | mortality using naval stations, capped at 250             |
| logmortnaval2250 | log mortality using naval stations capped at 250          |
| mortnaval1250    | mortality using naval stations, capped at 250             |
| logmortnaval1250 | log mortality using naval stations capped at 250          |
</details>

## Разведывательный анализ данных

Проведите разведывательный анализ данных: 

1. Постройте таблицу с описательными статистиками основных переменных.

2. Постройте графики, визуализирующие изучаемую взаимосвязь.


## Регрессионный анализ

Проведите регрессионный анализ: 

1. Оцените базовую модель парной регрессии. Рассчитайте робастные стандартные ошибки. 

2. Оцените изучаемую взаимосвязь с использованием инструментальных переменных и двухшагового метода наименьших квадратов: 

* используйте функцию `ivreg()` из пакета `AER`, рассчитайте робастные стандартные ошибки. 

* попробуйте повторить результаты, используя функцию `lm()`. 

3. Сведите результаты оценки всех регрессий в одну таблицу. 

4. Проинтерпретируйте полученные результаты.

5. Оформите скрипт R так, чтобы он был понятным и воспроизводимым. 


## Бонусы

1. Пробуйте ориентироваться на материалы статьи и "воспроизвести" графики и таблицы, которые используют авторы.

2. Обсудите, как можно было бы оценить подобные модели для случая множественной регрессии. Произведите оценивание в R.