---
title: "**Эконометрика**"
author: "*В. Пырлик, Д. Терещенко, Ю. Балагула, К. Ефимов*"
date: "2022-23 учебный год"
output:  
  html_document:  
    self_contained: no  
    theme: cosmo
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 2
    css: extra.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

Вы на странице курса "Эконометрика" для студентов 3 курса ОП "Экономика" бакалавриата в 2022-23 учебном году. Здесь собраны материалы курса: ссылки на слайды и записи занятий, дополнительные материалы, некоторые объявления.

Лекции проходят в 16:20 по пятницам [по постоянной ссылке в Zoom](https://cesnet.zoom.us/j/96338482138).

Записи занятий, слайды, заметки и прочие материалы можно найти по ссылкам ниже.

*Курс в процессе реализации. Страница обновляется по мере появления новых материалов.*

</br>

---

:::: {.infobox .deadline}

## **12.11 до 20:00** [**ЧЕРНОВИК ОТЧЕТА I**](ecox22/project_task_part03_report_draft.html)

::::

---

# 1. [Введение в курс](ecox22/sec1.html)

- Вкратце об эконометрике. Организация курса. Программа курса, формы работы, оценки.

- Повторение необходимых основ ТВиМС.

- Разное.

</br>

---

# 2. [Парная линейная регрессия](ecox22/sec2.html)

- Модель регрессии в среднем (введение).

- Модель парной линейной регрессии.

- Алгебра парной линейной регрессии.

- Эмпирический пример.

</br>

---

# 3. [Алгебра МНК в ММЛР](ecox22/sec3.html)

- Проблема пропущенных переменных

- Алгебра МНК в ММЛР

- Свойства оценок МНК параметров ММЛР

- Оценка матрицы ковариаций оценок МНК параметров ММЛР

- Эмпирические примеры

</br>

---

# 4. [Проверка гипотез и предельные эффекты в ММЛР](ecox22/sec4.html)

- Введение в диагностику ММЛР

- Постановка гипотез о параметрах в эконометрической модели

- Разные виды гипотез о параметрах

- Базовые предельыне эффекты в ММЛР

- Нелинейные предельные эффекты в ММЛР

*Раздел пополняется*

</br>

---

# [ПРОЕКТ](ecox22/project_task.html)

- Задание на проектную работу

*Раздел пополняется*

</br>

---

# [ОТЧЁТЫ ПО ЛЕТУЧКАМ](ecox22/quizzes.html)

*Раздел пополняется*

</br>

---

# *Дополнительно*

- [Все записи занятий в одном месте](https://drive.google.com/drive/folders/1iK9cVeiHyVJd2XSIXqzcfw199MLajSvJ?usp=sharing)

- [Все слайды в pdf](https://drive.google.com/drive/folders/1r4XjXynrU72cjN-XfGcz8EexEX4pXfYS?usp=sharing)

- ...

---

# *Контакты*

Вопросы можно задать [в чате в Телеграм.](https://t.me/+0kRsodLpmzRmZjEy)
